// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
}

interface Price {
    address: string;
    price: number;
}

interface Liquidity {
    address: string;
    a0: number;
    a1: number;
}